### PR TITLE
Updated population's `make_next_generation` method to bias towards best members of the prior generation

### PR DESCRIPTION
**Pull request by ebrynne**
Hello! Thanks for the awesome library, it's been a treat to use.

One issue that I had though, was that the current implementation of the parent selection in `population.rb` is set up such that every entry in the parent generation is guaranteed to have exactly two children in the following generation, whereas the [traditional implementation of a roulette-wheel selection algorithm](http://geneticalgorithms.ai-depot.com/Tutorial/Overview.html) biases towards the more-fit members of a population having more children in the next generation and the less fit parents might not have any children at all.

This changed provided optimal solutions for me in significantly fewer generations than the previous implementation so I figured I'd just submit it as a straight up switch, but if you'd prefer I'd be happy to reimplement it as toggled option or something like that?

Thanks!

Evan

### CODE REVIEW

**Comment by dorkrawk** [comment]
Awesome! I'm really glad you've enjoyed working with this library and I really appreciate the PR.

I think it will be find to just outright replace the existing mechanism. I'll check over things a bit more after work today and then merge.

**Comment by ebrynne** [comment]
Awesome! Thanks! And just let me know if there's anything else I can help with.

If you don't mind me asking, do you have any plans or timeline for updating the gem as well?

**Comment by dorkrawk** [comment]
Yea, I've been working on a feature that will allow you to just include Darwinning in existing models and then use those models as `Organisms` rather than creating special Darwinning models to do your GA stuff, but there are a few bugs I need to work out before I release another gem version.

**Comment by dorkrawk** [comment]
@ebrynne Hey, I just wanted to let you know that I released a new version of the gem last weekend. It has your updates in it, along with a bunch of other stuff. https://rubygems.org/gems/darwinning

**Pull request merged**
